import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/app/context/AuthContext";
import Navbar from "@/app/components/layout/navbar";
import Footer from "@/app/components/layout/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <AuthProvider>
            <div className="min-h-screen flex flex-col">
                <Navbar/>
                <div className="flex-grow container mx-auto px-4">
                    {children}
                </div>
                <Footer/>
            </div>
        </AuthProvider>
        </body>
    </html>
  );
}
